CREATE TABLE "Banners" (
    "Id" uuid NOT NULL,
    "Title" text,
    "ImageUrl" text NOT NULL,
    "LinkUrl" text,
    "Position" text NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Banners" PRIMARY KEY ("Id")
);


CREATE TABLE "BlogCategories" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Slug" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_BlogCategories" PRIMARY KEY ("Id")
);


CREATE TABLE "Brands" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Slug" text NOT NULL,
    "LogoUrl" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Brands" PRIMARY KEY ("Id")
);


CREATE TABLE "Categories" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Slug" text NOT NULL,
    "Description" text,
    "ImageUrl" text,
    "ParentId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Categories_Categories_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Categories" ("Id")
);


CREATE TABLE "Coupons" (
    "Id" uuid NOT NULL,
    "Code" text NOT NULL,
    "DiscountType" text NOT NULL,
    "DiscountValue" numeric(18,2) NOT NULL,
    "MinOrderAmount" numeric(18,2),
    "MaxDiscountAmount" numeric(18,2),
    "StartDate" timestamp with time zone,
    "EndDate" timestamp with time zone,
    "UsageLimit" integer,
    "UsedCount" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Coupons" PRIMARY KEY ("Id")
);


CREATE TABLE "Roles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);


CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "FullName" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);


CREATE TABLE "Products" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Slug" text NOT NULL,
    "Description" text NOT NULL,
    "BasePrice" numeric(18,2) NOT NULL,
    "IsFeatured" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "CategoryId" uuid NOT NULL,
    "BrandId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Products_Brands_BrandId" FOREIGN KEY ("BrandId") REFERENCES "Brands" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE
);


CREATE TABLE "RoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Addresses" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "RecipientName" text NOT NULL,
    "PhoneNumber" text NOT NULL,
    "Street" text NOT NULL,
    "City" text NOT NULL,
    "State" text,
    "ZipCode" text,
    "Country" text NOT NULL,
    "IsDefault" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Addresses_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "BlogPosts" (
    "Id" uuid NOT NULL,
    "Title" text NOT NULL,
    "Slug" text NOT NULL,
    "Content" text NOT NULL,
    "Excerpt" text,
    "ThumbnailUrl" text,
    "AuthorId" uuid,
    "CategoryId" uuid,
    "IsPublished" boolean NOT NULL,
    "PublishedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_BlogPosts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BlogPosts_BlogCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "BlogCategories" ("Id"),
    CONSTRAINT "FK_BlogPosts_Users_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "Users" ("Id")
);


CREATE TABLE "Carts" (
    "Id" uuid NOT NULL,
    "UserId" uuid,
    "SessionId" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Carts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Carts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);


CREATE TABLE "Orders" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "OrderNumber" text NOT NULL,
    "Status" text NOT NULL,
    "TotalAmount" numeric(18,2) NOT NULL,
    "SubTotal" numeric(18,2) NOT NULL,
    "ShippingCost" numeric(18,2) NOT NULL,
    "DiscountAmount" numeric(18,2) NOT NULL,
    "CouponCode" text,
    "ShippingAddress" text NOT NULL,
    "BillingAddress" text,
    "PaymentStatus" text NOT NULL,
    "PaymentMethod" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "RefreshTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Token" text NOT NULL,
    "Expires" timestamp with time zone NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "CreatedByIp" text NOT NULL,
    "Revoked" timestamp with time zone,
    "RevokedByIp" text,
    "ReplacedByToken" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "UserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "UserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "UserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "UserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ProductImages" (
    "Id" uuid NOT NULL,
    "Url" text NOT NULL,
    "IsMain" boolean NOT NULL,
    "ProductId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_ProductImages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductImages_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ProductVariants" (
    "Id" uuid NOT NULL,
    "Sku" text NOT NULL,
    "Color" text NOT NULL,
    "Size" text NOT NULL,
    "PriceAdjustment" numeric(18,2) NOT NULL,
    "StockQuantity" integer NOT NULL,
    "ProductId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_ProductVariants" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductVariants_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);


CREATE TABLE "OrderItems" (
    "Id" uuid NOT NULL,
    "OrderId" uuid NOT NULL,
    "ProductVariantId" uuid,
    "ProductName" text NOT NULL,
    "Sku" text NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "Quantity" integer NOT NULL,
    "Total" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Payments" (
    "Id" uuid NOT NULL,
    "OrderId" uuid NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "PaymentMethod" integer NOT NULL,
    "TransactionId" text,
    "Status" integer NOT NULL,
    "PaymentDate" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payments_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Shipments" (
    "Id" uuid NOT NULL,
    "OrderId" uuid NOT NULL,
    "TrackingNumber" text,
    "Carrier" text,
    "Status" text NOT NULL,
    "ShippedDate" timestamp with time zone,
    "EstimatedDeliveryDate" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Shipments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Shipments_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
);


CREATE TABLE "CartItems" (
    "Id" uuid NOT NULL,
    "CartId" uuid NOT NULL,
    "ProductVariantId" uuid NOT NULL,
    "Quantity" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_CartItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CartItems_Carts_CartId" FOREIGN KEY ("CartId") REFERENCES "Carts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CartItems_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants" ("Id") ON DELETE CASCADE
);


CREATE TABLE "InventoryTransactions" (
    "Id" uuid NOT NULL,
    "ProductVariantId" uuid NOT NULL,
    "QuantityChanged" integer NOT NULL,
    "TransactionType" text NOT NULL,
    "ReferenceId" uuid,
    "Note" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_InventoryTransactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InventoryTransactions_ProductVariants_ProductVariantId" FOREIGN KEY ("ProductVariantId") REFERENCES "ProductVariants" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ShipmentTracking" (
    "Id" uuid NOT NULL,
    "ShipmentId" uuid NOT NULL,
    "Status" text NOT NULL,
    "Location" text,
    "Description" text,
    "Timestamp" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_ShipmentTracking" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ShipmentTracking_Shipments_ShipmentId" FOREIGN KEY ("ShipmentId") REFERENCES "Shipments" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_Addresses_UserId" ON "Addresses" ("UserId");


CREATE INDEX "IX_BlogPosts_AuthorId" ON "BlogPosts" ("AuthorId");


CREATE INDEX "IX_BlogPosts_CategoryId" ON "BlogPosts" ("CategoryId");


CREATE INDEX "IX_CartItems_CartId" ON "CartItems" ("CartId");


CREATE INDEX "IX_CartItems_ProductVariantId" ON "CartItems" ("ProductVariantId");


CREATE INDEX "IX_Carts_UserId" ON "Carts" ("UserId");


CREATE INDEX "IX_Categories_ParentId" ON "Categories" ("ParentId");


CREATE UNIQUE INDEX "IX_Categories_Slug" ON "Categories" ("Slug");


CREATE UNIQUE INDEX "IX_Coupons_Code" ON "Coupons" ("Code");


CREATE INDEX "IX_InventoryTransactions_ProductVariantId" ON "InventoryTransactions" ("ProductVariantId");


CREATE INDEX "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");


CREATE UNIQUE INDEX "IX_Orders_OrderNumber" ON "Orders" ("OrderNumber");


CREATE INDEX "IX_Orders_UserId" ON "Orders" ("UserId");


CREATE INDEX "IX_Payments_OrderId" ON "Payments" ("OrderId");


CREATE INDEX "IX_ProductImages_ProductId" ON "ProductImages" ("ProductId");


CREATE INDEX "IX_Products_BrandId" ON "Products" ("BrandId");


CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");


CREATE UNIQUE INDEX "IX_Products_Slug" ON "Products" ("Slug");


CREATE INDEX "IX_ProductVariants_ProductId" ON "ProductVariants" ("ProductId");


CREATE UNIQUE INDEX "IX_ProductVariants_Sku" ON "ProductVariants" ("Sku");


CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");


CREATE INDEX "IX_RoleClaims_RoleId" ON "RoleClaims" ("RoleId");


CREATE UNIQUE INDEX "RoleNameIndex" ON "Roles" ("NormalizedName");


CREATE INDEX "IX_Shipments_OrderId" ON "Shipments" ("OrderId");


CREATE INDEX "IX_ShipmentTracking_ShipmentId" ON "ShipmentTracking" ("ShipmentId");


CREATE INDEX "IX_UserClaims_UserId" ON "UserClaims" ("UserId");


CREATE INDEX "IX_UserLogins_UserId" ON "UserLogins" ("UserId");


CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");


CREATE INDEX "EmailIndex" ON "Users" ("NormalizedEmail");


CREATE UNIQUE INDEX "UserNameIndex" ON "Users" ("NormalizedUserName");


CREATE TABLE "FeaturedSections" (
    "Id" uuid NOT NULL,
    "Title" text NOT NULL,
    "Subtitle" text,
    "GridColumns" integer NOT NULL DEFAULT 2,
    "DisplayOrder" integer NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_FeaturedSections" PRIMARY KEY ("Id")
);


CREATE TABLE "FeaturedSectionItems" (
    "Id" uuid NOT NULL,
    "FeaturedSectionId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "OverlayText" text,
    "LinkUrl" text,
    "ImageUrl" text,
    "DisplayOrder" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_FeaturedSectionItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FeaturedSectionItems_FeaturedSections_FeaturedSectionId" FOREIGN KEY ("FeaturedSectionId") REFERENCES "FeaturedSections" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_FeaturedSectionItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_FeaturedSectionItems_FeaturedSectionId" ON "FeaturedSectionItems" ("FeaturedSectionId");


CREATE INDEX "IX_FeaturedSectionItems_ProductId" ON "FeaturedSectionItems" ("ProductId");

